### PR TITLE
Not required node

### PR DESCRIPTION
**Pull request by sachingrover211**
Irrelevant node changes to mark description as incorrect
slider event logging code

### CODE REVIEW

**Comment by sachingrover211** [comment]
also for #285 #293

**Comment by jonwetzel** [comment]
@sachingrover211 I think I found a bug.  I merged this branch with master on my local and then tested it.  I created a drt model in author mode then did the following in student mode:

1. Add a quantity and choose an in-model description.
2. Choose the correct variable name
3. Click Done.
4. Click add quantity again.  The Description box is green even though its value is --Select--.

You might have to update this branch with master to see this bug.

**Comment by sachingrover211** [comment]
This is happening due to merging PR #317

**Comment by sachingrover211** [comment]
@jonwetzel I am looking at how to fix it. I know the line that is doing it and ensure the previous scenario as well.

**Comment by jonwetzel** [comment]
Code looks good to me.  Merging to master.

**Pull request merged**
