### PR TITLE
Regression Tests - Student Mode

### PR DESCRIPTION
**Pull request by dharanisakary**

### CODE REVIEW

**Comment by jonwetzel** [comment]
@dharanisakary Merge conflict detected.

**Comment by dharanisakary** [comment]
I have an other card to update regression tests as some code has changed. I think that PR will l take care of this?

**Comment by jonwetzel** [comment]
@dharanisakary Which PR is that?  I can't find it...

**Comment by jonwetzel** [comment]
Ok.  If this will be obsolete we can close this PR when the new PR comes up.  Let me know if that's the case, @dharanisakaray

**Comment by dharanisakary** [comment]
Hey @jonwetzel , I have updated same branch and this PR contains the changes for updated scripts.

**Comment by jonwetzel** [comment]
@dharanisakary What command should do you use to run the tests?

**Comment by dharanisakary** [comment]
gulp test

**Comment by jonwetzel** [comment]
@dharanisakary I'm getting the following error when I run gulp test... have you seen this one before?

jww@jww-OptiPlex-960 ~/Topomath/topomath/www $ gulp test
[15:53:22] Using gulpfile ~/Topomath/topomath/www/gulpfile.js
(node:3493) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[15:53:22] Starting 'test'...
module.js:472
    throw err;
    ^

Error: Cannot find module 'is-mergeable-object'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jww/Topomath/topomath/www/node_modules/deepmerge/index.js:1:87)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by dharanisakary** [comment]
No Jon, I haven't. Will explore on this and get back you.

**Pull request merged**
