### PR TITLE
Node editor ui integration changes

### LINKED ISSUE #77: ID not initialized in new model

### PR DESCRIPTION
**Pull request by sachingrover211**
resolves #77 (23746bd) #72 (201a7e7) #68 (201a7e7) #65 (multiple commits) #59 (acc4e54) #12 (f655369) #73 (f46cfd5) #96 (52f9245)

### CODE REVIEW

**Comment by sachingrover211** [comment]
@riteshsamala these comments are for the previous pull request right? So can we merge that pull request now and I will make these changes in this pull request? @jonwetzel what do you suggest.

**Comment by sachingrover211** [comment]
@jonwetzel @riteshsamala @dharanisakary all the bugs have been fixed and committed. If you can review the code changes that would be great. I will take a look at the code changes which were done by Ritesh and Dharani.

**Comment by sachingrover211** [comment]
@jonwetzel is this change still needed. I think I had explained it in the group?

**Comment by jonwetzel** [comment]
@sachingrover211 That change is no longer needed.  Priors do not need to appear until they are given a value by the user.

Will you be making a fix for the other bug where the equation node text doesn't update on the node itself on the canvas?

**Comment by sachingrover211** [comment]
@jonwetzel can we make a card for it and mark it as a bug? I didnt think about that scenario and I will make the code changes for it.

**Pull request merged**
