### PR TITLE
Schema recon2

### PR DESCRIPTION
**Pull request by riteshsamala**
issues addressed
https://github.com/Dragoon-Lab/topomath/issues/454
https://github.com/Dragoon-Lab/topomath/issues/471
https://github.com/Dragoon-Lab/topomath/issues/474
https://github.com/Dragoon-Lab/topomath/issues/475
https://github.com/Dragoon-Lab/topomath/issues/473
https://github.com/Dragoon-Lab/topomath/issues/472
https://github.com/Dragoon-Lab/topomath/issues/476
https://github.com/Dragoon-Lab/topomath/issues/477
https://github.com/Dragoon-Lab/topomath/issues/480
https://github.com/Dragoon-Lab/topomath/issues/479
last commit : couple of bugs related to 480 ( no issues for added for them, but need these to test 480 and also 479).

### CODE REVIEW

**Comment by jonwetzel** [comment]
@riteshsamala Author mode is erroring out without loading.  Any ideas?

image

**Comment by riteshsamala** [comment]
Yeah I fixed this bug, the code is on api branch ... I also made a commit to this branch as we are testing it currently. Will omit the commit on api branch when I raise a PR. Please test now

**Comment by jonwetzel** [comment]
Testing progress:

- [ ] #454
- [ ] #471
- [ ] #474
- [ ] #475
- [ ] #473
- [ ] #472
- [ ] #476
- [ ] #477
- [ ] #480
- [ ] #479

**Comment by riteshsamala** [comment]
Interesting, checking it now !

**Comment by jonwetzel** [comment]
Testing progress:

- [x] #454 Working in author and student.  6/27
- [ ] #471 and #474 Found a bug (see review above)
- [x] #475 
- [x] #473 Fixed 
- [ ] #472 See comment https://github.com/Dragoon-Lab/topomath/commit/a8f9161940e6ccda13be0cfd7bd936b607e838cb#commitcomment-34091727
- [x] #476  Working 6/27
- [x] #477 and #482 Schema table is updated properly.
- [ ] #480
- [ ] #479 See suggestion https://github.com/Dragoon-Lab/topomath/commit/628a45a4129610ba67ff1fe97a939c6fbeecb865

Test problem: test1/login.html/test620

**Comment by riteshsamala** [comment]
> If found a bug: when skip units is turned off, units says it's incorrect even when the user selects the right answer.
> image
> 
> Double check to make sure units works when not skipped.

In the author model, pdrinking does not have any units set as far as this case in concerned, will test the following bugs and see if this can be reproduced.

**Comment by jonwetzel** [comment]
@riteshsamala Giving DRTs still doesn't work for [the same problem I was testing earlier](https://github.com/Dragoon-Lab/topomath/pull/483#pullrequestreview-255436157).  For some reason it creates an alien node instead of sharing the variable between the two DRTs.

Starting that problem with restart problem and give DRTs checked gives:
image
The lower DRT should share the TJack variable, but it tries to create a TJill instead.

**Comment by jonwetzel** [comment]
Confirmed the bug with #472 (skip units) is fixed.  Units work in all 4 cross-cases of author-added-or-not x skip-units-or-not.

**Comment by jonwetzel** [comment]
Confirmed #471 and #474 bug is fixed.

**Comment by jonwetzel** [comment]
@vanlehn Aside from the bug 3 comments up on given-DRTs-with-a-shared-variable and the reappearance of #465, it looks like everything else is fixed.  New version is up on devel for your testing if you like.

**Comment by riteshsamala** [comment]
> For

Hi jon, 
From what I understood with discussions from kurt, TJill is the ideal auto generated name and user has to correct it later(even when drts are given). @vanlehn prof, can you please confirm this.

**Comment by vanlehn** [comment]
Yes, that’s correct.
--Kurt

**Pull request merged**
